### ISSUE TITLE
Opening a terminal crashes server

### ISSUE THREAD

**Issue by rmichaluszek** [game-design-driven/Create-Prepare-to-Dye#533]
Tested on **1.211.0** and **1.211.7**

Server generated using provided files and readme file on Modrinth App.

Opening the quest terminal in game crashes server with error:

> 
> Time: 2024-01-22 17:55:43
> Description: Ticking entity
> 
> java.lang.ExceptionInInitializerError: null
> 	at io.github.mortuusars.wares.block.entity.DeliveryTableBlockEntity.constant$zca004$validDistance(DeliveryTableBlockEntity.java:783) ~[wares-1.19.2-1.2.5.jar%23243!/:1.2.5] {re:mixin,re:classloading,pl:mixin:APP:ptdyeplus.mixins.json:wares.DeliveryTableBlockEntityMixin,pl:mixin:A}
> 	at io.github.mortuusars.wares.block.entity.DeliveryTableBlockEntity.m_6542_(DeliveryTableBlockEntity.java:562) ~[wares-1.19.2-1.2.5.jar%23243!/:1.2.5] {re:mixin,re:classloading,pl:mixin:APP:ptdyeplus.mixins.json:wares.DeliveryTableBlockEntityMixin,pl:mixin:A}
> 	at io.github.mortuusars.wares.menu.DeliveryTableMenu.m_6875_(DeliveryTableMenu.java:134) ~[wares-1.19.2-1.2.5.jar%23243!/:1.2.5] {re:classloading}
> 	at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayer.java:416) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:pluto.mixins.json:player.ServerPlayerMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.drop_exp_with_keep_inventory.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.disable_night_skip.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.source_dependent_iframes.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.can_breathe_water.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.permanent_conduit_power.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.permanent_dolphins_grace.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.no_hunger.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.taggable_players.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.hide_armor.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:a_fixes.sync_attacker_yaw.MixinServerPlayerEntity,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
> 	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A}
> 	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.water_fills_on_break.MixinWorld,pl:mixin:A}
> 	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A}
> 	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:collections.entity_ticking.EntityTickListMixin,pl:mixin:A}
> 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
> 	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
> 	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
> Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
> 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:1.0] {}
> 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
> 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
> 	at com.kikis.ptdyeplus.PtdyePlus.<clinit>(PtdyePlus.java:40) ~[ptdyeplus-1.3.11+forge-1.19.2.jar%23227!/:1.3.11+forge-1.19.2] {re:mixin,re:classloading}
> 	... 15 more
> 
> -- Head --
> Thread: Server thread
> Suspected Mods: 
> 	Wares (wares), Version: 1.2.5
> 		at TRANSFORMER/wares@1.2.5/io.github.mortuusars.wares.block.entity.DeliveryTableBlockEntity.constant$zca004$validDistance(DeliveryTableBlockEntity.java:783)
> 
> 	Ptdye Plus (ptdyeplus), Version: 1.3.11+forge-1.19.2
> 		Mixin class: com.kikis.ptdyeplus.mixin.wares.DeliveryTableBlockEntityMixin
> 		Target: io.github.mortuusars.wares.block.entity.DeliveryTableBlockEntity
> 		at TRANSFORMER/wares@1.2.5/io.github.mortuusars.wares.block.entity.DeliveryTableBlockEntity.constant$zca004$validDistance(DeliveryTableBlockEntity.java:783)
> Stacktrace:
> 	at io.github.mortuusars.wares.block.entity.DeliveryTableBlockEntity.constant$zca004$validDistance(DeliveryTableBlockEntity.java:783) ~[wares-1.19.2-1.2.5.jar%23243!/:1.2.5] {re:mixin,re:classloading,pl:mixin:APP:ptdyeplus.mixins.json:wares.DeliveryTableBlockEntityMixin,pl:mixin:A}
> 	at io.github.mortuusars.wares.block.entity.DeliveryTableBlockEntity.m_6542_(DeliveryTableBlockEntity.java:562) ~[wares-1.19.2-1.2.5.jar%23243!/:1.2.5] {re:mixin,re:classloading,pl:mixin:APP:ptdyeplus.mixins.json:wares.DeliveryTableBlockEntityMixin,pl:mixin:A}
> 	at io.github.mortuusars.wares.menu.DeliveryTableMenu.m_6875_(DeliveryTableMenu.java:134) ~[wares-1.19.2-1.2.5.jar%23243!/:1.2.5] {re:classloading}
> 	at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayer.java:416) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:pluto.mixins.json:player.ServerPlayerMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.drop_exp_with_keep_inventory.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.disable_night_skip.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.source_dependent_iframes.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.can_breathe_water.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.permanent_conduit_power.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.permanent_dolphins_grace.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.no_hunger.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.taggable_players.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.hide_armor.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:a_fixes.sync_attacker_yaw.MixinServerPlayerEntity,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
> 	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A}
> 	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.water_fills_on_break.MixinWorld,pl:mixin:A}
> 	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A}
> 	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:collections.entity_ticking.EntityTickListMixin,pl:mixin:A}
> 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A}
> -- Entity being ticked --

Deleting the Ptdye Plus mod breaks the interface ( cant open the second tab in inventory, and also you cant finish contracts, meaning the arrow doesnt load if you place required items, and sometimes even first eq slot in terminal is bugged - items dissapear from it )

**Comment by EngineerSmith** [comment]
I can't seem to replicate this issue. I'm running a dedicated server with a fresh install and neither the client or server crash when trying to open the trading terminal. Then it seems to complete trades fine. So it may of been fixed in another update we've done.

Was this a fresh server install, or was it a server updated with the `update-server` script?

**Comment by rmichaluszek** [comment]
server-update script, and it doesn't crash anymore on 1.211.26, but now trading is impossible due to dissapearing and bugged gui items in trading terminal. (items flicker, randomly dissapears forever - we lost the only on first trading contract due to this bug)

**Comment by jasperalani** [comment]
hm, the code in DeliveryTableBlockEntityMixin doesnt seem like it could cause that much damage. any idea on whats happening @EngineerSmith
