### ISSUE TITLE
"IllegalArgumentException: Cannot set property IntegerProperty" when hoppering items into bare shaft

### ISSUE THREAD

**Issue by copygirl** [game-design-driven/Create-Prepare-to-Dye#572]
Modpack version: `1.211.44`

Built a simple milk to raw white machine, with hoppers going into a crate. I destroyed the crate and put down a shaft in place of it. The game crashed and keeps crashing when attempting to log back into the world. In case it helps, [this is when it happened to me on stream](https://twitch.tv/videos/2049861157?t=04h41m38s) (as long as the VOD is available). However, I can reproduce the issue in a creative world.

### How to reproduce

- Place down crate
- Place down hopper into the crate
- Fill hopper with items
- Break crate
- Place shaft in place of crate

Unsure if every step is required. Could not cause the crash without first placing the crate. Due to the bug causing the world to become unplayable I only reproduced the issue once. World generation takes a long time. :sweat_drops:

### Stacktrace

```
java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=fullness, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5]} as it does not exist in Block{create:shaft}
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at com.kikis.ptdyeplus.block.entity.BaseContainerEntity.updateBlockState(BaseContainerEntity.java:198) ~[ptdyeplus-1.5.6+forge-1.19.2.jar%23273!/:1.5.6+forge-1.19.2] {re:classloading}
	at com.kikis.ptdyeplus.block.entity.BaseContainerEntity.m_6596_(BaseContainerEntity.java:185) ~[ptdyeplus-1.5.6+forge-1.19.2.jar%23273!/:1.5.6+forge-1.19.2] {re:classloading}
	at com.kikis.ptdyeplus.block.entity.BaseContainerEntity.m_6836_(BaseContainerEntity.java:129) ~[ptdyeplus-1.5.6+forge-1.19.2.jar%23273!/:1.5.6+forge-1.19.2] {re:classloading}
	at net.minecraftforge.items.wrapper.InvWrapper.insertItem(InvWrapper.java:85) ~[forge-1.19.2-43.3.2-universal.jar%23296!/:?] {re:classloading}
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertStack(VanillaInventoryCodeHooks.java:170) ~[forge-1.19.2-43.3.2-universal.jar%23296!/:?] {re:classloading}
	at net.minecraftforge.items.VanillaInventoryCodeHooks.putStackInInventoryAllSlots(VanillaInventoryCodeHooks.java:144) ~[forge-1.19.2-43.3.2-universal.jar%23296!/:?] {re:classloading}
	at net.minecraftforge.items.VanillaInventoryCodeHooks.lambda$insertHook$2(VanillaInventoryCodeHooks.java:123) ~[forge-1.19.2-43.3.2-universal.jar%23296!/:?] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:108) ~[forge-1.19.2-43.3.2-universal.jar%23296!/:?] {re:classloading}
	at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:134) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:HopperBlockEntityAccessor,pl:mixin:APP:canary.mixins.json:entity.hopper_minecart.HopperBlockEntityMixin,pl:mixin:A}
	at net.minecraft.world.level.block.entity.HopperBlockEntity.m_155578_(HopperBlockEntity.java:105) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:HopperBlockEntityAccessor,pl:mixin:APP:canary.mixins.json:entity.hopper_minecart.HopperBlockEntityMixin,pl:mixin:A}
	at net.minecraft.world.level.block.entity.HopperBlockEntity.m_155573_(HopperBlockEntity.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:HopperBlockEntityAccessor,pl:mixin:APP:canary.mixins.json:entity.hopper_minecart.HopperBlockEntityMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.water_fills_on_break.MixinWorld,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23291!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
```

I assume it has something to do with the crate (that has a `fullness` property?) and perhaps its block entity is not being destroyed properly? Since the mod is exclusive to the pack, but I'm not sure if it's specifically its fault, I figured I'd report it here.

**Comment by copygirl** [comment]
I'm a little worried that fixing the bug that causes the crash won't necessarily fix the crash itself.

Should I be prepared to start a new world?

**Comment by copygirl** [comment]
Another issue that occurs in relation to crates: Destroying a crate and placing a toolbox in place of it renders the toolbox inaccessible. Once you move the toolbox you can also see that its contents are gone.

**Comment by Yarden-zamir** [comment]
Looking into this. I do not think you'll need a new world, for now what you can do is turn on `removeErroringBlockEntities` in the `world/serverconfig/forge-server.toml` and avoid the crates until the fix

**Comment by copygirl** [comment]
I believe this got fixed with game-design-driven/ptdye-plus@54e6c934ea1e599ef9fffc76d79b2497005ad043. A quick test after updating seems to confirm this?
